[functions.verify-is-admin]
enabled = true
verify_jwt = true
entrypoint = "./functions/verify-is-admin/index.ts"

[functions.handle-identity-token]
enabled = true
verify_jwt = false
entrypoint = "./functions/handle-identity-token/index.ts"

[functions.cashout]
enabled = true
verify_jwt = true
entrypoint = "./functions/cashout/index.ts"