export const ROUTES = {
  start: '/',
  login: '/login',
  register: '/register',
  characterSelect: '/character-select',
  creatureSelect: '/creature-select',
  profileConfirmation: '/profile-confirmation',
  gameMenu: '/game-menu',
  lobby: '/lobby',
  battle: '/battle',
  battleSession: '/battle/:sessionId',
  battleResult: '/battle-result',
  adminLogin: '/admin-login',
  adminPanel: '/admin-panel',
  shop: '/shop',
  help: '/help',
  credits: '/credits',
  profile: '/profile',
} as const
